services:
  selenium-hub4:
    image: selenium/hub:latest
    container_name: selenium-hub4
    ports:
      - "4441:4441"
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
  chrome1:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome2:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome3:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443      
      
  chrome4:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome5:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome6:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443      
